language: sh

branches:
  only:
  - test

os:
  - linux
  
before_install:
  - sudo apt-get update
  - sudo apt-get install -y python3 python3-setuptools python3-pip python3-sphinx

script:
  - pip3 install .
  - cd ./docs/ 
  - bash ./gendoc.sh
  - cd ../
  
deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh
    on:
       branch: test
